# crew/config/api_keys.yml
# Archivo local para tus claves de API.
# NO subir a GitHub ni compartir!

fmp:
  api_key: "YOUR_FMP_API_KEY"

alpha_vantage:
  api_key: "YOUR_ALPHA_VANTAGE_API_KEY"

finnhub:
  api_key: "YOUR_FINNHUB_API_KEY"
